### ISSUE TITLE
Document escaping ${foo}

### ISSUE THREAD

**Issue by Profpatsch** [nikita-volkov/neat-interpolation#12]
I searched for a way to escape ${foo} (since nix expressions use ${} for string splicing themselves) and I found $${foo} worked. Maybe document that?

**Comment by nikita-volkov** [comment]
Can you make a PR please?

**Comment by Profpatsch** [comment]
> Can you make a PR please?

Yes, I need to know two things first:
1. Is that intended behaviour?
2. Do you set the escape in the module or is it inherited from the way QuasiQuotes work?

**Comment by nikita-volkov** [comment]
It's intended. The dollar escaping is achieved with double dollar:

https://github.com/nikita-volkov/neat-interpolation/blob/master/library/NeatInterpolation/Parsing.hs#L24
