### ISSUE TITLE
`text` eats all empty lines in the beginning  and the end of the output 

### ISSUE THREAD

**Issue by vrom911** [nikita-volkov/neat-interpolation#16]
If you have something like this:
```haskell
myText = [text|


v I really need that lines  ^.


|]
```
you expect to have the output:
```
> myText


v I really need that lines  ^.


```
But instead it's just 
```
> myText
v I really need that lines  ^.
```
My workaround was to have the `endLine = "\n"` and put it at first and last lines:
```haskell
myText = [text|
$endline

v I really need that lines  ^.

$endline
|]
```
which is not very cool.
It would be much nicer if this behavior can be configurable.

**Comment by nikita-volkov** [comment]
Yours is really a rare case, but anyways. Here's a new behaviour that I suggest:

```haskell
myText1 =
  [text|
    abc
  |]

myText2 =
  [text|
  
    abc
  |]
  
myText3 =
  [text|

    abc

  |]
  

myText1 == "abc"
myText2 == "\nabc"
myText3 == "\nabc\n"
```

**Comment by nikita-volkov** [comment]
The difference from the current behaviour will be that instead of trimming all the blank lines, it will only drop 1 from each side (if they are at all present).

**Comment by vrom911** [comment]
@nikita-volkov  Okay, I see now. That'll do for me.

**Comment by nikita-volkov** [comment]
0.5 now provides `trimming` and `untrimming` variations of the quasiquoter. `untrimming` addresses the problem expressed in this thread.
