### ISSUE TITLE
🚀 v0.3.2.3 to Hackage

### ISSUE THREAD

**Issue by werediver** [nikita-volkov/neat-interpolation#21]
Currently the last version of neat-interpolation on Hackage is 0.3.2.2 and the latest version in this repository is 0.3.2.3. Would be very nice to have it on Hackage 🙂

It is especially important, because [brittany](https://github.com/lspitzner/brittany) depends on this package, and this package depends on Megaparsec, and if somebody (like me) wants to use brittany in a project depending on Megaparsec 7 he/she will need neat-interpolation-0.3.2.3.

**Comment by nikita-volkov** [comment]
Fixed
