### ISSUE TITLE
Please add support for current versions of megaparsec and HTF

### ISSUE THREAD

**Issue by peti** [nikita-volkov/neat-interpolation#24]
http://packdeps.haskellers.com/feed?needle=neat-interpolation

![Screenshot_2019-12-03 Newer dependencies for neat-interpolation](https://user-images.githubusercontent.com/28323/70038307-5015e780-15b8-11ea-8a7f-9749da10c7d9.png)

**Comment by peti** [comment]
I ran the build with megaparsec 8.x, and it succeeded just fine. I reckon that all there is to it is to edit the Cabal file an Hackage to relax the upper bound.

**Comment by nikita-volkov** [comment]
Done! Thanks for reporting
