### ISSUE TITLE
Reintroduce `text` for backward compatibility. 

### ISSUE THREAD

**Issue by slpopejoy** [nikita-volkov/neat-interpolation#25]
A plea to maintain backward compatibility in this library. It seems ungenerous to require users who were happy with `text` to change. 

IIUC, `text` is now `trimming`, which if your code had `[text| ... |]` all over it (and you were happy with it, as we are), now you have a far more opaque name. Personally I'd rather not be reminded over and over about a single property of the text interpolator; `text` is beautifully communicative of the larger intent, which is to simply interpolate text. But that's a matter of opinion.

However, what is not opinion, is that this library introduced `text`.  To take it away, and break downstream code, should be avoided if possible, as a general rule. `text` was in no way a terrible name, so keeping it as a synonym of `trimming` does no harm and is respectful of users who are maintaining codebases that use this library. Yes, it's a tiny library, but in a way that makes the change worse: it breaks 100% of the API.

If my argument is persuasive, I'm happy to submit a PR to this effect. EDIT opened PR, why not.

**Comment by nikita-volkov** [comment]
Wow. This must be really bugging you. I'm wondering why running a simple search and replace on the codebase is considered so dreadful..?

My another intention was to make the users pay attention to the changes, because neither of these quasiqouters behaves exactly as the old `text`. There was an old bug: a trailing newline was always being added to any input.

**Comment by nikita-volkov** [comment]
Any way. I've merged your PR. But still please provide a feedback on this:

> I'm wondering why running a simple search and replace on the codebase is considered so dreadful..? Or adding an alias in your own code?

**Comment by slpopejoy** [comment]
To my mind it's obvious, don't break working code that is used by others, if you don't have to, ever. 

What is funny here is, `text` is a great QQ verb, and far superior to the `i`s and `s`s in other libs, while still being short. I didn't design that -- but have been very satisfied with it. So I'm in the strange position of arguing for the merit of your old code.

I say this because of course everything is a matter of opinion at some point. But backcompat shouldn't be, a metric should be applied so that you avoid Windows 3.1-style backcompat-of-death, but otherwise leave working code alone. 

For me that metric is: "was the old code bad/misleading/an excessive maintenance problem", ie something where a bad design is imposing a terrible cost that must be undone at whatever cost. (Bugs are obviously different.)

Here I would say that metric was not met:
1. The old solution was good, great even. Yes it chomps by default, but hey, I like it.
2. The upgrade is trivially easy to do with backcompat, and imposes minimal maintenance burden. 
3. Subjectively, I don't think the new verbs are better, so I oppose the breaking change full stop. They're longer, they focus on one parameter (trimming) at the cost of overall comprehension. Looking ahead, what if a new feature comes along for say "lenient-utf". Are we going to get the product of `trimming` + `lenient-utf` as a breaking change, and go to 16+ char verbs?

Finally, a note from the user side: we have production code that uses `text` in multiple projects. "a simple search and replace" is not accurate as of course there are gotchas, so this slows down a team, requires review etc. I would rather spend the time convincing you to maintain backcompat so I can continue to have confidence in using the library. 

In any case, thanks for the lib, it really is the best one for the purpose, and thanks for listening and accepting my PR.

**Comment by nikita-volkov** [comment]
Okay. Thanks. The `text` function is restored in `0.5.1`.
