### ISSUE TITLE
neat-interpolation unusable without OverloadedStrings?

### ISSUE THREAD

**Issue by ethercrow** [nikita-volkov/neat-interpolation#27]
If I understand correctly `sigE (appE [|Text.intercalate "\n"|] $ listE $ map lineExp lines) [t|Text|]` causes this compilation failure at usage site:

```
    • Couldn't match expected type ‘T.Text’ with actual type ‘[Char]’
    • In the first argument of ‘T.intercalate’, namely ‘"
"’
      In the expression:
        ((T.intercalate "
")
           [T.pack "<?xml version="1.0" encoding="UTF-8"?>",
            T.pack
              "<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://w",
            T.pack "/PropertyList-1.0.dtd">", T.pack "<plist version="1.0">",
            ....] ::
           T.Text)
```

Unfortunately I can't easily enable `OverloadedStrings` in this module because it uses Shake a lot and Shake doesn't play well OverloadedStrings. The simplest workaround is probably to put shake stuff and multiline interpolations into separate files.

**Comment by nikita-volkov** [comment]
Should be fixed in the latest release

**Comment by ethercrow** [comment]
Thanks!
