### ISSUE TITLE
Example in haddocks misses languages extensions 

### ISSUE THREAD

**Issue by ulysses4ever** [nikita-volkov/neat-interpolation#30]
Example reads:
```
import NeatInterpolation
import Data.Text (Text)

f :: Text -> Text -> Text
f a b =
  [trimming|
    function(){
      function(){
        $a
      }
      return $b
    }
  |]
```
Given that imports are there I expect it to be a standalone example that is runnable. But that's not true: it misses:
```
{-# LANGUAGE QuasiQuotes, OverloadedStrings #-}
```
Would it be possible to add these? I think it will make the documentation friendlier.

**Comment by nikita-volkov** [comment]
Good idea! Could you PR?

**Comment by ulysses4ever** [comment]
Oh, this is funny: the source does have the language pragma (no need in OverloadedStrings, of course), but Haddock did not render it for some reason:

* [source](https://hackage.haskell.org/package/neat-interpolation-0.5.1.2/docs/src/NeatInterpolation.html) 
* [rendered](https://hackage.haskell.org/package/neat-interpolation-0.5.1.2/docs/NeatInterpolation.html)

It seems like Haddock's bug...

**Comment by ulysses4ever** [comment]
Okay, this seems to be a known (mis)feature of Haddock: https://github.com/haskell/haddock/issues/1254 which may or may not be fixed in the future. The workaround is to use single-line comments. Submitted #31 with the workaround, but I will understand if you won't be willing to accept it.
