### ISSUE TITLE
Please add a README

### ISSUE THREAD

**Issue by andreasabel** [nikita-volkov/neat-interpolation#32]
Please add a README with some representative use-case.

**Comment by nikita-volkov** [comment]
Could you PR?

**Comment by andreasabel** [comment]
I came here via https://github.com/sol/interpolate/issues/17#issue-643816777, so I was curious what neat-interpolation is about.  
To answer your question: No, I have no clue what neat-interpolation is about.

**Comment by nikita-volkov** [comment]
Well, the Hackage doc is pretty exhaustive
