### ISSUE TITLE
string function always inserts a newline

### ISSUE THREAD

**Issue by proger** [nikita-volkov/neat-interpolation#4]
Hello,

``` haskell
λ> [string|hello|]
"hello\n"
```

Is it possible to control this behaviour?

**Comment by nikita-volkov** [comment]
Of course, it's possible. Can you please make a pull-request? I'm currently swamped.

**Comment by nikita-volkov** [comment]
Fixed in 0.4 and 0.5. Starting from 0.5 the `trimming` quasi-quoter removes all leading and trailing whitespace.

**Comment by proger** [comment]
Thank you!
