### ISSUE TITLE
Use 'fromString' to allow interpolation of e.g. Text

### ISSUE THREAD

**Issue by neongreen** [nikita-volkov/neat-interpolation#6]
~~~ haskell
-- | A quasiquoter that produces any textual value instead of 'String'.
text :: QuasiQuoter
text = QuasiQuoter {
  quoteExp = appE [|fromString|] . quoteExp string,
  quotePat = quotePat string,
  quoteType = quoteType string,
  quoteDec = quoteDec string }
~~~

Something like this. (Or perhaps it should be done in `string` itself?)

**Comment by neongreen** [comment]
I can make a pull request if you're still swamped, but it's your decision whether it's alright to do in `string` or whether it might lead to lots of “ambiguous type” errors (and thus a new quasiquoter would be better).

**Comment by nikita-volkov** [comment]
I have long planned to switch to `Text` altogether. If you can make such a PR it would be nice.

**Comment by neongreen** [comment]
Okay, so which of these should it be?

1. switch to `Text` altogether and don't use `fromString` at all
2. just switch to `Text` internally but use `fromString` (to let people use it without conversion when e.g. lazy `Text` is required)
3. don't switch anything but create `text` (which would follow 1.)
4. don't switch anything but create `text` (which would follow 2.)
5. let `text` use `Text` and switch `string` to use `fromString` (so, `string` becomes more universal)

**Comment by nikita-volkov** [comment]
> switch to Text altogether and don't use fromString at all

I vote for that.

> just switch to Text internally but use fromString (to let people use it without conversion when e.g. lazy Text is required)

Going from strict to lazy Text is an O(1) operation. So it really doesn't matter much.

**Comment by neongreen** [comment]
Okay, I guess this can be closed?
